# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
version: 0.2
env:
  secrets-manager:
    SONAR_TOKEN: "SonarQubeUserSecret-Oa8WDsR0iMmt:SONAR_TOKEN"
    SONAR_HOST_URL: "SonarQubeUserSecret-Oa8WDsR0iMmt:SONAR_HOST_URL"
    ORGANIZATION: "SonarQubeUserSecret-Oa8WDsR0iMmt:Organization"
    PROJECT: "SonarQubeUserSecret-Oa8WDsR0iMmt:Project"

phases:
  install:
    runtime-versions:
      java: corretto17

    commands:
      - apt-get update -y
      - apt-get install -y maven
      - pip3 install --upgrade awscli
      - echo "Configuring Git for AWS CodeCommit..."
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - wget https://dlcdn.apache.org/maven/maven-3/3.8.9/binaries/apache-maven-3.8.9-bin.tar.gz
      - tar xzf apache-maven-3.8.9-bin.tar.gz
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.3.0.5189-linux-x64.zip
      - unzip ./sonar-scanner-cli-7.3.0.5189-linux-x64.zip
      - export PATH=$PATH:/sonar-scanner-7.3.0.5189-linux/bin/


  pre_build:
    commands:
      - sonar_host_url="http://16.171.165.134:9000"
      - sonar_project_key="$PROJECT"
      - sonar_username=$(aws secretsmanager get-secret-value --secret-id $SONARQUBE_USER_CREDENTIAL_SECRET | jq -r '.SecretString' | jq -r '.username')
      - sonar_password=$(aws secretsmanager get-secret-value --secret-id $SONARQUBE_USER_CREDENTIAL_SECRET | jq -r '.SecretString' | jq -r '.password')
      - git checkout $SOURCE_COMMIT

  build:
    commands:
      - mvn license:format
      - mvn clean install 
      - mvn clean verify sonar:sonar -Dsonar.projectKey=$PROJECT  -Dsonar.projectName=$PROJECT -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.token=$SONAR_TOKEN
      - sleep 5
      - curl http://16.171.165.134:9000/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
      
  
artifacts:
  files: '**/*'
