# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
version: 0.2
env:
  secrets-manager:
    LOGIN: sonar-test-secretkey:sonartoken
    HOST: sonar-test-secretkey:HOST
    Organization: sonar-test-secretkey:Organization
    Project: sonar-test-secretkey:Project
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq
      - wget https://dlcdn.apache.org/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz
      - tar -xzf apache-maven-3.9.11-bin.tar.gz
      - wget https://repo1.maven.org/maven2/org/sonarsource/scanner/cli/sonar-scanner-cli/4.6.2.2472/sonar-scanner-cli-4.6.2.2472-linux.zip
      - unzip sonar-scanner-cli-4.6.2.2472-linux.zip
      - export PATH=$PATH:/sonar-scanner-4.6.2.2472-linux/bin
  build:
    commands:     
      - mvn install
      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sleep 5
      - curl https://sonarcloud.io/project/overview?id=devops-cg_aws-codecommit-pull-request-approver-demo-master >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
          
artifacts:
  files: '**/*'
