# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
version: 0.2
phases:
  build:
    commands:
      - mvn clean install
      - mvn verify sonar:sonar -Dsonar.projectKey=sample_project -Dsonar.organization=sampeproject -Dsonar.host.url=http://51.20.95.70:9000/ -Dsonar.login=squ_040414b1f8d4e92d9a29d94e44fc137d530b6544 
